### PR TITLE
Drops visualization

### PR DESCRIPTION
**Pull request by crozzfire**

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
Hi Souvik,

Sorry it's taken me so long to look at this.  Overall the new "drops" visualization looks very promising; thanks for integrating it into DIG.  I see that it's currently used for the locations on the offer page; where else do you expect it to be used?  Will it replace the "Summary of Provider Attributes"?  Will it replace the Bar Chart?

Since there have been some changes in the past few weeks with how queries are built that caused issues with the merge, I've created a branch in which I've merged your pull request and made the changes to fix the querying:
https://github.com/NextCenturyCorporation/digapp-ht/tree/crozzfire-Drops-Visualization
Please feel free to merge this into your repo.

In my changes, the drops timeline now only shows locations for a specific offer rather than locations for the phone number(s) in an offer (since those drops timelines would belong on the phone entity pages).  I've also changed the interval of the date histogram from hours to days since I'm concerned with timeouts for large queries.

There are a couple of issues I'd like you to investigate.  First, if you set the width of the drops timeline container to the width of the column, the drops SVG is set to be much smaller than the container when it should instead fill the whole container.  Second, the date labels tend to overlap each other at some zoom levels.  Third, if you click on the drops timeline and drag up out of the SVG (instead of left or right to pan) then the data disappears and the date range is set to "NaN".  Some or all of these may be bugs in the Event Drops library but it would be good to make sure they're not caused by something in the DIG implementation.

Finally, please add unit tests for your new transforms and fix all errors generated by the "gulp lint" command (note that some of the line numbers from the polymer files may be off because it has to extract the code in the script tags into a temporary file).

Thanks!

**Comment by crozzfire** [comment]
@ThomasSchellenbergNextCentury Thanks a ton for the merge fixes! I was a bit concerned about that earlier. Some of my thoughts for your questions:
1. _"Will it replace the "Summary of Provider Attributes"? Will it replace the Bar Chart?"_ : I remember during our initial conversations with @szeke , he had mentioned that it would replace the BarChart. 
2. _" I've also changed the interval of the date histogram from hours to days since I'm concerned with timeouts for large queries."_ : That makes sense. I also had added a little change earlier, which would offset same timestamps, which prevents two data points from overlapping.
3. _"if you set the width of the drops timeline container to the width of the column, the drops SVG is set to be much smaller than the container when it should instead fill the whole container"_ : This is actually a known issue in my implementation and I had already spent a whole lotta time to try to fix it. It turns out to be some very strange race during the DOM initializations and none of the "general" way of setting the SVG size to fill the container during runtime worked. Would love to brainstorm about this. I'll write in detail about it in my next comment.
4. _"the date labels tend to overlap each other at some zoom levels"_ : This is a bug in the lib itself :( But also indirectly related to the the container width issue.
5. _"if you click on the drops timeline and drag up out of the SVG (instead of left or right to pan) then the data disappears and the date range is set to NaN"_ : Thanks for the report, I'll look into it.

Meanwhile, as you had mentioned, I'll wrap it up with the unit tests. Would you want me to add those changes to the same PR or create another one?

Thanks a bunch again!

**Comment by ThomasSchellenbergNextCentury** [comment]
@crozzfire 

For number 3, it sounds like it won't be an easy fix.  I don't want this to be a blocker for the pull request since everything still works well enough (it's just a bit small).  We can address it later.

For the unit tests, please add them to this pull request.

Thanks!

**Comment by crozzfire** [comment]
@ThomasSchellenbergNextCentury Sorry for getting back so late. I'm done with the unit testing the drops-timeline-transform , fixed all the jslint errors. The labels turning to NaN seems to be a event drops lib issue, which I'm looking into to find some workaround. Although, there is a strange behavior lately, I can't somehow seem to find an example ES aggregate response with multiple documents. I was just wondering if its due to a query change or something. It'll be great if you can look into that sometime, so that I can add that as a test case. I'll push my changes out by tomorrow after digging in some more in the lib which is causing both the issues (width not fitting the container and the dragging to NaN). Thanks!

**Comment by ThomasSchellenbergNextCentury** [comment]
@crozzfire 

In response to "I can't seem to find an example ES aggregate response with multiple documents":

If I understand you correctly, this issue is probably due to changing the "drops" query on the offer page to match only documents with the same offer ID rather than the same offer phone number, since I believe that should always match a single document.  If it helps you for testing purposes, you can change the the "drops" query to use the offer phone number by replacing the offerQuery variable with a new custom query built like this (replacing phoneField and phone as appropriate):

```
    <elastic-client-query-builder
      type="term"
      field="phoneField"
      values="phone"
      ejs-query="{{testQuery}}">
    </elastic-client-query-builder>
```

**Comment by crozzfire** [comment]
@ThomasSchellenbergNextCentury You're absolutely right, completely overlooked it. Also I think it should always be the phone(s)/email(s) of the seller because we want to plot _all_ the offers from the same seller over the course of time. Let me know if that makes sense. That said, the offer's page might seem a little out of place for such a feature ... but its good for a first release I guess?

**Comment by ThomasSchellenbergNextCentury** [comment]
@crozzfire The offer page should just show data for the offer itself, not for other offers.  The seller/phone/email pages would show drops timelines for all offers for that seller/phone/email.  Including data from other offers on an offer page would completely change how the application works conceptually which I don't think we're planning to do at this time.

I agree that the drops timeline would be useful to implement on other entity pages.  My impression from previous discussions with @szeke was that the drops timeline would be used everywhere that the blue and orange horizontal bars were currently used.  I'm not sure if he intended for that to be a gradual change or done all-at-once.

**Comment by crozzfire** [comment]
@ThomasSchellenbergNextCentury Hmm yeah that makes sense. Sorry I wasn't aware that it would appear in multiple places. In that case, I'll just push my changes with some simple tests and gradually add as we keep adding the drops timeline to different pages.

**Comment by ThomasSchellenbergNextCentury** [comment]
@crozzfire I have merged your branch.  A couple of comments:
1. We _never_ want to include raw data in our unit tests since the data is sensitive and this is a public repository.  All of our test data is saved in the DIG Data repository and any sensitive values that need to be referenced in our tests are cleaned (for example, changing an email address to "abc@xyz.com").  I have added your test data (and expanded upon it a bit) to the offer aggregations test data file and rewrote the tests to use this file, which you can see in this commit:
   https://github.com/NextCenturyCorporation/digapp-ht/commit/4f4d06fdc257f54aefbdd91caa7a5d86d153648c
   Please remember to do this when you write tests in the future.
2. I had to cleanup multiple lint errors in the files.  Please remember to run "gulp lint" and fix the issues before you submit a pull request next time.

Overall, though, good work.  Thanks for your contribution!

Thomas

**Pull request merged**
